# Site settings
title:          깨방정의 코딩 diary     # Meta 태그에 들어가는 영역
subtitle:       by 호기심이 많은
description:    "Daye's Today I learned"     # Meta 태그에 들어가는 영역
url:            "https://dayebyday.github.io"     # GitBlog 호스트 주소
teaser:         # 홈페이지 기본 티져 이미지
logo:           # 타이틀 옆에 작게 들어갈 이미지

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         dayebyday
  url:          https://dayebyday.github.io
  email:        mdaye15@gmail.com

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/dayebyday/dayebyday.github.io

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         dayebyday

# Collection
collections_dir:
  my_collections
